# Answer 분석 상태
ANSWER_STATUS_PENDING = "PENDING"
ANSWER_STATUS_PROCESSING = "PROCESSING"
ANSWER_STATUS_DONE = "DONE"
ANSWER_STATUS_FAILED = "FAILED"

# 분석 모듈
MODULE_VISUAL = "visual"
MODULE_VOICE = "voice"
MODULE_CONTENT = "content"
